### ISSUE TITLE
I compiled this example but waiting a long time

### ISSUE THREAD

**Issue by ifew** [rubin55/dot-hello#1]
Now I developing some native app for using EF Core MySQL but waiting a long time, I not sure to correct or not.

and then try to pull your code and compile, it's wait long time too 

I don't know why?

My OS: MacOS Mojave
CPU Intel Core i5 2.9 GHz
Memory:	8 GB

**Comment by ifew** [comment]
After waiting more than 1 hour

```bash
  Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeCoreRT
EXEC : warning : RD.XML processing will change before release (https://github.com/dotnet/corert/issues/5001) [/Users/chitpong/Sourcecode/dot-hello/hello.csproj]
  Process is terminating due to StackOverflowException.
  /var/folders/j_/dz2fhccj2b97xx_lv7mgvnv00000gn/T/tmpa6f40bc79f2049ab8c129c7319a41bd3.exec.cmd: line 2: 65131 Abort trap: 6           "/Users/chitpong/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27527-01/tools/ilc" @"obj/release/netcoreapp2.1/osx-x64/native/hello.ilc.rsp"
/Users/chitpong/.nuget/packages/microsoft.dotnet.ilcompiler/1.0.0-alpha-27527-01/build/Microsoft.NETCore.Native.targets(239,5): error MSB3073: The command ""/Users/chitpong/.nuget/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/1.0.0-alpha-27527-01/tools/ilc" @"obj/release/netcoreapp2.1/osx-x64/native/hello.ilc.rsp"" exited with code 134. [/Users/chitpong/Sourcecode/dot-hello/hello.csproj]
$ 
```

**Comment by rubin55** [comment]
Haven't touch this example in a while; would need to see if I can reproduce. When I ran this initially, It worked and compile time wasn't abnormally long (seconds rather than minutes). Usually, this suggests a too wide class specification in rd.xml.

If I have a moment later today, I'll see if I can reproduce.

**Comment by rubin55** [comment]
I just reproduced this with both dotnet 2.2 and 2.1. I don't know what changed though. Will dig a little deeper.

**Comment by ifew** [comment]
Thank you for reply,

This is my code
https://github.com/ifew/aws-lambda-lambdanative-db/tree/master/src/aws-lambda-lambdanative

And I don't understand how to write rd.xml, I try to use wildecards but it too slow

```xml
<Assembly Name="*Application*" Dynamic="Required All"/>
```

**Comment by ifew** [comment]
> I haven't touched this code in a while! I'd need to see if I can reproduce this. When I ran this initially, It worked and compile time wasn't abnormally long (seconds rather than minutes). Usually, this suggests a too wide class specification in rd.xml. I suppose you added lines to reflect the usage of MySQL? could you show me the lines you edited or added to rd.xml?
> 
> If I have a moment later today, I'll see if I can reproduce.

This I used in rd.xml, I think this wide class but I don't know how to get in deep

```xml
<?xml version="1.0" encoding="utf-8"?>
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <Assembly Name="LambdaNative" Dynamic="Required All" />
    <Assembly Name="aws-lambda-lambdanative" Dynamic="Required All" />

    <Assembly Name="Microsoft.EntityFrameworkCore.Relational" Dynamic="Required All" />
    <Assembly Name="MySql.Data.EntityFrameworkCore" Dynamic="Required All" />
    <Assembly Name="MySql.Data" Dynamic="Required All" />
    <Assembly Name="Microsoft.Extensions.Configuration.FileExtensions" Dynamic="Required All" />
    <Assembly Name="Microsoft.Extensions.Configuration.EnvironmentVariables" Dynamic="Required All" />
    <Assembly Name="System.Security.Principal.Windows" Dynamic="Required All" />
    <Assembly Name="System.Security.AccessControl" Dynamic="Required All" />
    <Assembly Name="System.Security.Cryptography.ProtectedData" Dynamic="Required All" />
    <Assembly Name="System.Security.Permissions" Dynamic="Required All" />
    <Assembly Name="System.Text.Encoding.CodePages" Dynamic="Required All" />
    <Assembly Name="System.Configuration.ConfigurationManager" Dynamic="Required All" />
    <Assembly Name="Google.Protobuf" Dynamic="Required All" />
    <Assembly Name="Amazon.Lambda.Core" Dynamic="Required All" />
    <Assembly Name="Amazon.Lambda.Serialization.Json" Dynamic="Required All" />
    <Assembly Name="Amazon.Lambda.APIGatewayEvents" Dynamic="Required All" />
  </Application>
</Directives>
```

**Comment by ifew** [comment]
> I just reproduced this with both dotnet 2.2 and 2.1. I don't know what changed though. Will dig a little deeper.

I still a problem with your example code, Maybe root cause from environment issues?

Our environment
dotnet 2.2.104
cmake 3.14.2
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
OS: MacOS Mojave
CPU: Intel Core i5 2.9 GHz
Memory: 8 GB

**Comment by ifew** [comment]
After I changed from  https://github.com/dotnet/corert/issues/7333
I can compile and run your code :D

And then I still to fighting my code T-T
